;;lucram numai cu arbori binari
(defvar tree '(1 (2 (3) (4)) (5 (6) (7))))
(defvar tree1 '(1 ((2 ()) (3 ()))))

(DEFUN preorder (tree)
    (WHEN (NOT (NULL tree))
        (prin1 (CAR tree))
        (preorder (CADR tree))
        (preorder (CADDR tree))
    )
)

(DEFUN inorder (tree)
    (WHEN (NOT (NULL tree))
        (preorder (CADR tree))
        (prin1 (CAR tree))
        (preorder (CADDR tree))
    )
)

(DEFUN postorder (tree)
    (WHEN (NOT (NULL tree))
        (preorder (CADR tree))
        (preorder (CADDR tree))
        (prin1 (CAR tree))
    )
)

(preorder tree)
(preorder tree1)
(inorder tree)
(inorder tree1)
(postorder tree)
(postorder tree1)